### Get /
GET http://localhost:4500/

### Register User POST /auth/register
POST http://localhost:4500/auth/register
Content-Type: application/json

{
    "username": "test@gmail.com",
    "password": "password"
}

### Login User POST /auth/login
POST http://localhost:4500/auth/login
Content-Type: application/json

{
    "username": "test@gmail.com",
    "password": "password"
}

### Get all todos GET /todos (protected)
GET http://localhost:4500/todos
Authorization: ### Insert JWT token here


### Create new todo POST /todos (protected)
POST http://localhost:4500/todos
Authorization: ### Insert JWT token here
Content-Type: application/json

{
    "task": "Finish application"
}

### Update Todo PUT /TODOS/:ID (protected)
PUT http://localhost:4500/todos/2
Authorization: ### Insert JWT token here

{
    "completed": 1
}

### Delete Todo DELETE /TODOS/:ID (protected)
DELETE http://localhost:4500/todos/
Authorization: ### Insert JWT token here